"""
app.py — Streamlit dashboard for the Baghewala Well-to-Surface Digital Twin
prototype (SIH26120).

DEMONSTRATION ONLY. Uses synthetic data and simplified engineering
relationships. Not field-calibrated. Not a reservoir simulator. Must not
be used for operational decisions without validation against approved
field data and domain-expert review. See README for full scope.
"""

import os
import sys

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

sys.path.insert(0, os.path.dirname(__file__))

from digital_twin import physics
from digital_twin.simulator import CycleConfig, simulate_cycle, cycle_summary
from digital_twin.optimizer import optimize_cycle
from digital_twin.data_gen import generate_dataset
from digital_twin.ml_models import (
    train_all, save_models, load_models, PRODUCTION_FEATURES, THERMAL_FEATURES, RISK_FEATURES,
)

st.set_page_config(page_title="Baghewala Digital Twin", layout="wide")

MODEL_DIR = "saved_models"


@st.cache_resource(show_spinner="Training models on synthetic data (first run only)...")
def get_models():
    """Load saved models if present, otherwise generate data + train + save."""
    try:
        return load_models(MODEL_DIR), None
    except FileNotFoundError:
        df = generate_dataset(n_cycles=300)
        models = train_all(df)
        save_models(models, MODEL_DIR)
        return models, models.metrics


models, fresh_metrics = get_models()

st.title("Baghewala well-to-surface digital twin")
st.caption(
    "SIH26120 — Oil India Limited · Prototype / decision-support demo · "
    "synthetic data, not field-calibrated"
)

with st.expander("Safety & scope banner — read before demoing", expanded=False):
    st.warning(
        "This system is a **non-autonomous decision-support prototype**. "
        "It does not and must not control physical wellhead chokes, steam "
        "boilers, or SRP VFDs. All recommendations require human "
        "petroleum-engineer review before any field action. Data shown is "
        "synthetically generated by the physics module in this repo, not "
        "real Oil India telemetry."
    )

tab_sim, tab_opt, tab_ml, tab_about = st.tabs(
    ["Cycle simulator", "CSS + SRP optimizer", "ML model performance", "About this prototype"]
)

# ---------------------------------------------------------------------
# TAB 1 — Cycle simulator (what-if sandbox)
# ---------------------------------------------------------------------
with tab_sim:
    st.subheader("What-if CSS cycle simulator")
    c1, c2, c3, c4 = st.columns(4)
    steam_volume = c1.slider("Steam volume (bbl)", 1000, 7000, 4000, step=250)
    soak_days = c2.slider("Soak duration (days)", 1, 12, 5)
    spm = c3.slider("SPM (strokes/min)", 1.5, 8.0, 4.0, step=0.5)
    stroke_in = c4.slider("Stroke length (in)", 54, 120, 86, step=2)

    cfg = CycleConfig(
        steam_volume_bbl=steam_volume,
        soak_days=soak_days,
        produce_days=40,
        spm=spm,
        stroke_length_in=stroke_in,
    )
    df = simulate_cycle(cfg)
    summary = cycle_summary(df, steam_volume)

    k1, k2, k3, k4 = st.columns(4)
    k1.metric("Peak temperature", f"{summary['peak_temp_c']:.1f} C")
    k2.metric("Cumulative oil", f"{summary['cumulative_oil_bbl']:.0f} bbl")
    k3.metric("Steam-oil ratio", f"{summary['steam_oil_ratio']:.2f}")
    k4.metric(
        "Days with floating risk",
        summary["floating_days"],
        delta=None if summary["floating_days"] == 0 else "check pump settings",
        delta_color="inverse",
    )

    if summary["max_floating_risk_ratio"] >= 1.0:
        st.error(
            f"Rod-floating criterion met on {summary['floating_days']} day(s) "
            f"of this cycle (peak risk ratio {summary['max_floating_risk_ratio']:.2f}). "
            "Consider lowering SPM or increasing soak time."
        )
    elif summary["max_floating_risk_ratio"] >= 0.8:
        st.warning(
            f"Rod-floating risk approaching threshold (peak ratio "
            f"{summary['max_floating_risk_ratio']:.2f}). Monitor closely."
        )

    col_a, col_b = st.columns(2)
    with col_a:
        fig = go.Figure()
        fig.add_trace(go.Scatter(x=df["day"], y=df["temp_c"], name="Temperature (C)"))
        fig.add_trace(go.Scatter(x=df["day"], y=df["viscosity_cp"], name="Viscosity (cP)", yaxis="y2"))
        fig.update_layout(
            title="Thermal decay & viscosity rebound",
            xaxis_title="Day",
            yaxis=dict(title="Temperature (C)"),
            yaxis2=dict(title="Viscosity (cP)", overlaying="y", side="right"),
            legend=dict(orientation="h"),
            height=380,
        )
        st.plotly_chart(fig, use_container_width=True)

    with col_b:
        fig2 = go.Figure()
        fig2.add_trace(go.Scatter(x=df["day"], y=df["oil_rate_bopd"], name="Oil rate (BOPD)"))
        fig2.add_trace(go.Scatter(x=df["day"], y=df["rod_floating_risk_ratio"], name="Floating risk ratio", yaxis="y2"))
        fig2.add_hline(y=1.0, line_dash="dash", line_color="red", annotation_text="floating threshold", yref="y2")
        fig2.update_layout(
            title="Production & rod-floating risk",
            xaxis_title="Day",
            yaxis=dict(title="Oil rate (BOPD)"),
            yaxis2=dict(title="Risk ratio", overlaying="y", side="right"),
            legend=dict(orientation="h"),
            height=380,
        )
        st.plotly_chart(fig2, use_container_width=True)

    with st.expander("Show raw simulated daily data"):
        st.dataframe(df, use_container_width=True)

# ---------------------------------------------------------------------
# TAB 2 — Optimizer
# ---------------------------------------------------------------------
with tab_opt:
    st.subheader("Joint CSS + SRP optimizer (pump-survivable steam)")
    st.write(
        "Grid-searches steam volume, soak duration, and SPM to maximise "
        "cumulative oil net of steam cost, **rejecting any combination "
        "that crosses the rod-floating risk threshold** — production is "
        "never optimised at the expense of pump survivability."
    )
    risk_limit = st.slider("Max allowed floating-risk ratio", 0.5, 1.2, 0.85, step=0.05)

    if st.button("Run optimization", type="primary"):
        with st.spinner("Evaluating candidate operating points..."):
            result = optimize_cycle(risk_limit=risk_limit)

        st.success("Recommended pump-safe CSS + SRP plan:")
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Steam volume", f"{result.best_config.steam_volume_bbl:.0f} bbl")
        c2.metric("Soak duration", f"{result.best_config.soak_days} days")
        c3.metric("SPM", f"{result.best_config.spm:.1f}")
        c4.metric("Predicted cumulative oil", f"{result.best_summary['cumulative_oil_bbl']:.0f} bbl")

        st.caption(
            f"Steam-oil ratio: {result.best_summary['steam_oil_ratio']:.2f}  |  "
            f"Peak floating-risk ratio: {result.best_summary['max_floating_risk_ratio']:.2f}  |  "
            f"{result.rejected_for_risk} of {len(result.all_results)} candidate settings "
            "rejected for exceeding the risk limit"
        )

        results_df = pd.DataFrame([
            dict(
                steam_bbl=r["cfg"].steam_volume_bbl,
                soak_days=r["cfg"].soak_days,
                spm=r["cfg"].spm,
                cum_oil_bbl=r["summary"]["cumulative_oil_bbl"],
                sor=r["summary"]["steam_oil_ratio"],
                max_risk_ratio=r["summary"]["max_floating_risk_ratio"],
                feasible=r["feasible"],
            )
            for r in result.all_results
        ])
        st.dataframe(results_df.sort_values("cum_oil_bbl", ascending=False), use_container_width=True)

# ---------------------------------------------------------------------
# TAB 3 — ML model performance
# ---------------------------------------------------------------------
with tab_ml:
    st.subheader("ML surrogate model performance")
    st.write(
        "These models are trained on the synthetic dataset produced by the "
        "physics simulator (not real field data — see About tab). They "
        "demonstrate the modelling approach; real performance figures must "
        "be re-measured once trained on Oil India's historical CSS/SRP data."
    )

    if fresh_metrics:
        metrics = fresh_metrics
    else:
        # models were loaded from disk with no metrics attached — retrain once to display metrics
        df = generate_dataset(n_cycles=300)
        _, metrics = train_all(df), None
        retrained = train_all(df)
        metrics = retrained.metrics

    c1, c2, c3 = st.columns(3)
    with c1:
        st.markdown("**Production forecaster**")
        st.metric("MAE", f"{metrics['production_mae']:.2f} BOPD")
        st.metric("R²", f"{metrics['production_r2']:.4f}")
    with c2:
        st.markdown("**Thermal decay predictor**")
        st.metric("MAE", f"{metrics['thermal_mae_c']:.2f} C")
        st.metric("R²", f"{metrics['thermal_r2']:.4f}")
    with c3:
        st.markdown("**Rod-floating / failure risk classifier**")
        st.metric("Accuracy", f"{metrics['risk_accuracy']:.1%}")
        st.metric("Precision / Recall", f"{metrics['risk_precision']:.2f} / {metrics['risk_recall']:.2f}")

    st.info(
        "High R² / accuracy here reflects the model learning the "
        "*simulator's* internal logic well, not real-world field accuracy. "
        "This is expected and appropriate for a synthetic-data prototype — "
        "see README for the real-data validation step that remains."
    )

# ---------------------------------------------------------------------
# TAB 4 — About
# ---------------------------------------------------------------------
with tab_about:
    st.subheader("About this prototype")
    st.markdown(
        """
This is a **hackathon-stage prototype** for SIH26120 (Oil India Limited —
Digital Twin for Well-to-Surface Optimization of CSS and SRP Operations,
Baghewala Field). It demonstrates the full architecture end-to-end on
**synthetic data** generated by the physics module in this repo.

**What it demonstrates**
- A physics layer implementing the Walther viscosity equation, a
  hydrodynamic rod-floating criterion, and simplified API RP 11L beam
  loads
- A coupled CSS + SRP daily simulator (`digital_twin/simulator.py`)
- Three ML surrogate models trained on simulator-generated data
- A constrained optimizer that treats rod-floating risk as a hard limit,
  not a soft penalty
- An interactive what-if dashboard (this app)

**What it does not demonstrate (see README for full list)**
- Real Oil India field data / SCADA integration
- MATLAB-based PDE thermal simulation (reimplemented in Python here for
  portability — architecture designed for MATLAB swap-in)
- Reinforcement-learning SPM control (optimizer here is grid search)
- Field-calibrated physics constants

Full source, README, and roadmap: see the linked GitHub repository.
        """
    )
